# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LIANGZHE
email: michaelluang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site made with Jekyll and a whole bunch of love by Liang Zhe,
  who is a college student, a front-end developer, a fitness
  fanatic and a lifelong learner. 
keywords: "Productivity, Creativity, Time Management, JavaScript, Web Development, Front-end Developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://michaelluang.github.io/" # the base hostname & protocol for your site
twitter_username: michaelluang
github_username:  michaelluang
instagram_username: michaelluang

# Where things are
sass:
  sass_dir: ./assets/_sass

# Build settings
markdown: kramdown
